### PR TITLE
Add support for PHP 8.2, Remove support for PHP 7.4

### PR DESCRIPTION
**Pull request by gsteel**
|    Q          |   A
|-------------- | ------
| New Feature   | yes

### Description

Probably needs https://github.com/laminas/laminas-validator/pull/156 and a lock refresh to avoid `ignore-platform-reqs`

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]

**Comment by Ocramius** [comment]
Hmm, should release validator first?

**Comment by gsteel** [comment]
That should do it!

**Comment by Ocramius** [comment]
`laminas/laminas-validator` released with https://github.com/laminas/laminas-validator/pull/156 included: this can go in, as soon as it has an adjusted `composer.json`

**Comment by Ocramius** [comment]
Thanks @gsteel!

**Pull request merged**
