### PR TITLE
ArrayAccess arg type in BaseInputFilter::validateInputs()

### PR DESCRIPTION
**Pull request by darckking**
Signed-off-by: illia <illia.gapak@ffflabel.com>

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description

I described the problem on Laminas forums, you can find it here
https://discourse.laminas.dev/t/arrayaccess-arg-type-in-baseinputfilter-validateinputs/2567
The test I added illustrates 2 problems:
1. Wrong behavior on PHP >7.4 because array_key_exists doesn't call for ArrayAccess::offsetExists()
2. Deprecation warning on PHP 7.4, I believe PHP 8 will throw an error, haven't tested that.

At least I expect that ArrayAccess will be removed from DocBlock of BaseInputFilter::validateInputs(), but ideally validateInputs() $data argument must be typed as an array. When min PHP version will change to 7.4 - BaseInputFilter::$data typed as an array as well. After this fixed - my test has to be removed or BaseInputFilter::validateInputs() must get proper support for ArrayAccess object.

### CODE REVIEW

**Comment by froschdesign** [comment]
@darckking 
Please check the failed checks:

* https://github.com/laminas/laminas-inputfilter/runs/4048519547?check_suite_focus=true#step:3:309
* https://github.com/laminas/laminas-inputfilter/runs/4048519683?check_suite_focus=true#step:3:350
* https://github.com/laminas/laminas-inputfilter/runs/4048519768?check_suite_focus=true#step:3:350

Thanks in advance! 👍

**Comment by darckking** [comment]
> @darckking Please check the failed checks:
> 
> * https://github.com/laminas/laminas-inputfilter/runs/4048519547?check_suite_focus=true#step:3:309
> * https://github.com/laminas/laminas-inputfilter/runs/4048519683?check_suite_focus=true#step:3:350
> * https://github.com/laminas/laminas-inputfilter/runs/4048519768?check_suite_focus=true#step:3:350
> 
> Thanks in advance! 👍

**Comment by darckking** [comment]
@froschdesign 
Hi
What exactly should I check ?
Yes, the test I added fails. But that is my goal to show that there is a problem. When I use ArrayAccess argument which is allowed according to annotation.
7.3 - wrong result.
7.4  - deprecation warning
8 - type error

**Comment by froschdesign** [comment]
@darckking 
> Yes, the test I added fails. But that is my goal to show that there is a problem.

You are right. Thank you for the reminder!
Would you also provide a solution?

**Comment by darckking** [comment]
@froschdesign 

> At least I expect that ArrayAccess will be removed from DocBlock of BaseInputFilter::validateInputs(), but ideally validateInputs() $data argument must be typed as an array. When min PHP version will change to 7.4 - BaseInputFilter::$data typed as an array as well. After this fixed - my test has to be removed or BaseInputFilter::validateInputs() must get proper support for ArrayAccess object.

Basically it depends on how important it is to have ArrayAccess as argument. If no - then remove it, if yes - then ArrayAccess::offsetExists() must be used instead of array_key_exists() in BaseInputFilter line 261

**Comment by froschdesign** [comment]
@darckking 
> …then remove it…

It is a bug in DocBlocks, so go for it.
Thanks in advance! 👍

**Comment by darckking** [comment]
I removed ArrayAccess and created another pull request [#46 ](https://github.com/laminas/laminas-inputfilter/pull/46).
I close this pull request because the test I added is not relevant anymore after ArrayAccess removal.

**Pull request closed without merging**
